# Generated by Django 3.1.1 on 2020-09-26 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ques_generator', '0002_auto_20200909_1048'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=20)),
            ],
        ),
    ]
